server:
  port: 8081

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
        http:
          server:
            reactive: TRACE
        web:
          reactive: TRACE
    reactor:
      netty:
        http:
          client: DEBUG
pokemon:
  limit: 151
  color: red
