server:
  port: 8080

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
